name: coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev cmake gcovr lcov

      - name: Build GTest
        run: |
          cd /usr/src/googletest
          sudo cmake .
          sudo cmake --build . --config Release
          sudo cp googlemock/gtest/*.a /usr/lib

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build Project & Tests
        run: cmake --build ${{github.workspace}}/build

      - name: Run Tests
        run: |
          cd ${{github.workspace}}/build
          ctest -j2

      - name: Generate Coverage
        run: |
          cd ${{github.workspace}}/build
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./build/coverage.info
