name: coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev cmake gcovr lcov

      - name: Build Project & Tests
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          make

      - name: Run Tests
        run: |
          cd ${{github.workspace}}/build
          ctest -j2

      - name: Generate Coverage
        run: |
          cd ${{github.workspace}}/build
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '*/unittests/*' '/usr/*' --output-file coverage.info

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./build/coverage.info
